name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ Instala el ANDROID SDK + herramientas necesarias (API 35)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: '35.0.0'

      # Descarga Gradle y genera el wrapper (porque no lo tenemos en repo)
      - name: Install Gradle and generate wrapper
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.7/bin" >> $GITHUB_PATH
          gradle -v
          gradle wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Compila APK debug
      - name: Build Debug APK
        run: ./gradlew clean assembleDebug --stacktrace --no-daemon

      # Sube el APK como artefacto descargable
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
